// frontend/src/pages/Cart.vue
<script setup lang="ts">
import { ref, computed, h, watch, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { DeleteOutlined, ShoppingOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import { useCustomerStore } from '../stores/customer'
import { useCartStore } from '../stores/cart'
import { getProduct } from '../api/products'
import { createOrder } from '../api/orders'

const router = useRouter()
const customerStore = useCustomerStore()
const cartStore = useCartStore()

const products = ref<Record<number, any>>({})
const submitting = ref(false)

const current = computed(() => customerStore.current)
const items = computed(() => cartStore.items)

watch(() => current.value?.id, (id) => {
  if (id) cartStore.fetch(id)
})

watch(() => items.value, () => {
  loadProducts()
})

async function loadProducts() {
  const map: Record<number, any> = {}
  for (const item of items.value) {
    if (!products.value[item.product_id]) {
      const res = await getProduct(item.product_id)
      map[item.product_id] = res.data
    }
  }
  products.value = { ...products.value, ...map }
}

const total = computed(() =>
  items.value.reduce((sum, item) => {
    const p = products.value[item.product_id]
    return sum + (p ? p.price * item.quantity : 0)
  }, 0)
)

const totalQuantity = computed(() =>
  items.value.reduce((s, i) => s + i.quantity, 0)
)

async function handleCheckout() {
  if (!current.value || items.value.length === 0) return
  submitting.value = true
  try {
    await createOrder(current.value.id)
    cartStore.clear()
    message.success('下单成功！')
    router.push('/orders')
  } catch {
    message.error('下单失败')
  }
  submitting.value = false
}

onMounted(() => {
  if (current.value) cartStore.fetch(current.value.id)
})
</script>

<template>
  <div style="max-width: 800px; margin: 0 auto; padding: 48px 0">
    <h3 style="font-size: 21px; font-weight: 600; margin-bottom: 24px">🛒 购物车</h3>

    <a-empty v-if="!current" description="请先选择身份" />

    <template v-else-if="items.length === 0">
      <a-empty description="购物车是空的">
        <a-button type="primary" @click="router.push('/')">去逛逛</a-button>
      </a-empty>
    </template>

    <template v-else>
      <a-card
        v-for="item in items"
        :key="item.id"
        style="margin-bottom: 12px"
      >
        <div style="display: flex; justify-content: space-between; align-items: center">
          <div>
            <div style="font-weight: 600; margin-bottom: 4px">
              {{ products[item.product_id]?.name || '加载中...' }}
            </div>
            <div>
              <a-tag color="blue">{{ products[item.product_id]?.category }}</a-tag>
              <span style="margin-left: 8px; color: #7a7a7a; font-size: 14px">
                ¥{{ products[item.product_id]?.price }}/件
              </span>
            </div>
          </div>
          <div style="display: flex; align-items: center; gap: 12px">
            <a-input-number
              :min="1"
              :max="products[item.product_id]?.stock || 99"
              :value="item.quantity"
              @change="(v: number | null) => current && cartStore.updateItem(current.id, item.id, v || 1)"
              style="width: 80px"
            />
            <span style="font-weight: 600; color: #ff4d4f; min-width: 80px; text-align: right">
              ¥{{ products[item.product_id] ? (products[item.product_id].price * item.quantity).toFixed(2) : '--' }}
            </span>
            <a-popconfirm
              title="确定移除？"
              @confirm="current && cartStore.removeItem(current.id, item.id)"
            >
              <a-button danger :icon="h(DeleteOutlined)" />
            </a-popconfirm>
          </div>
        </div>
      </a-card>

      <a-card style="margin-top: 16px">
        <div style="display: flex; justify-content: space-between; align-items: center">
          <span>共 {{ totalQuantity }} 件商品</span>
          <div style="display: flex; align-items: center; gap: 16px">
            <span>
              合计:
              <span style="font-weight: 600; color: #ff4d4f; font-size: 24px">¥{{ total.toFixed(2) }}</span>
            </span>
            <a-button
              type="primary"
              size="large"
              @click="handleCheckout"
              :loading="submitting"
            >
              <ShoppingOutlined /> 立即下单
            </a-button>
          </div>
        </div>
      </a-card>
    </template>
  </div>
</template>

// frontend/src/pages/Cart.tsx
import { useEffect, useState } from 'react'
import { Card, Typography, Button, List, InputNumber, Empty, message, Popconfirm, Space, Tag } from 'antd'
import { DeleteOutlined, ShoppingOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { useCustomerStore } from '../stores/customerStore'
import { useCartStore } from '../stores/cartStore'
import { getProduct } from '../api/products'
import { createOrder } from '../api/orders'

const { Title, Text } = Typography

export default function Cart() {
  const navigate = useNavigate()
  const { current } = useCustomerStore()
  const { items, fetch, updateItem, removeItem, clear } = useCartStore()
  const [products, setProducts] = useState<Record<number, any>>({})
  const [submitting, setSubmitting] = useState(false)

  useEffect(() => {
    if (current) fetch(current.id)
  }, [current?.id])

  useEffect(() => {
    loadProducts()
  }, [items])

  async function loadProducts() {
    const map: Record<number, any> = {}
    for (const item of items) {
      if (!products[item.product_id]) {
        const res = await getProduct(item.product_id)
        map[item.product_id] = res.data
      }
    }
    setProducts((prev) => ({ ...prev, ...map }))
  }

  const total = items.reduce((sum, item) => {
    const p = products[item.product_id]
    return sum + (p ? p.price * item.quantity : 0)
  }, 0)

  async function handleCheckout() {
    if (!current || items.length === 0) return
    setSubmitting(true)
    try {
      await createOrder(current.id)
      clear()
      message.success('下单成功！')
      navigate('/orders')
    } catch {
      message.error('下单失败')
    }
    setSubmitting(false)
  }

  if (!current) return <Empty description="请先选择身份" />

  return (
    <div style={{ maxWidth: 800, margin: '0 auto' }}>
      <Title level={3}>🛒 购物车</Title>
      {items.length === 0 ? (
        <Empty description="购物车是空的">
          <Button type="primary" onClick={() => navigate('/')}>去逛逛</Button>
        </Empty>
      ) : (
        <>
          <List
            dataSource={items}
            renderItem={(item) => {
              const p = products[item.product_id]
              return (
                <Card style={{ marginBottom: 12 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                      <Text strong>{p?.name || '加载中...'}</Text>
                      <div>
                        <Tag color="blue">{p?.category}</Tag>
                        <Text type="secondary" style={{ marginLeft: 8 }}>¥{p?.price}/件</Text>
                      </div>
                    </div>
                    <Space>
                      <InputNumber
                        min={1} max={p?.stock || 99}
                        value={item.quantity}
                        onChange={(v) => current && updateItem(current.id, item.id, v || 1)}
                        style={{ width: 80 }}
                      />
                      <Text strong style={{ color: '#ff4d4f', minWidth: 80, textAlign: 'right' }}>
                        ¥{p ? (p.price * item.quantity).toFixed(2) : '--'}
                      </Text>
                      <Popconfirm title="确定移除？" onConfirm={() => current && removeItem(current.id, item.id)}>
                        <Button danger icon={<DeleteOutlined />} />
                      </Popconfirm>
                    </Space>
                  </div>
                </Card>
              )
            }}
          />
          <Card style={{ marginTop: 16 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Text>共 {items.reduce((s, i) => s + i.quantity, 0)} 件商品</Text>
              <Space>
                <Text>合计: <Text strong style={{ color: '#ff4d4f', fontSize: 24 }}>¥{total.toFixed(2)}</Text></Text>
                <Button type="primary" size="large" icon={<ShoppingOutlined />}
                  onClick={handleCheckout} loading={submitting}>
                  立即下单
                </Button>
              </Space>
            </div>
          </Card>
        </>
      )}
    </div>
  )
}
