// frontend/src/pages/MarketingApproval.tsx
import { useEffect, useState } from 'react'
import { Tag, Button, Space, message, Spin, Modal, Input } from 'antd'
import { CheckOutlined, CloseOutlined, ReloadOutlined } from '@ant-design/icons'
import client from '../api/client'

const { TextArea } = Input

interface Strategy {
  id: number; merchant_id: number; strategy_type: string; title: string;
  description: string; proposed_changes: Record<string, any>;
  status: string; ai_reasoning: string; admin_comment: string; created_at: string | null
}
interface Merchant { id: number; name: string; ai_model: string; main_category: string; brand_color: string }

const TYPE_LABELS: Record<string, string> = {
  price_adjustment: '调价', promotion: '促销活动',
  bundle: '捆绑销售', recommendation_update: '推荐更新',
}

export default function MarketingApproval() {
  const [strategies, setStrategies] = useState<Strategy[]>([])
  const [merchants, setMerchants] = useState<Merchant[]>([])
  const [loading, setLoading] = useState(true)
  const [commentModal, setCommentModal] = useState<{ id: number; action: 'approve' | 'reject' } | null>(null)
  const [comment, setComment] = useState('')
  const [submitting, setSubmitting] = useState(false)

  const merchantMap = Object.fromEntries(merchants.map(m => [m.id, m]))

  useEffect(() => { loadData() }, [])

  async function loadData() {
    setLoading(true)
    const [sRes, mRes] = await Promise.all([
      client.get('/marketing/strategies'),
      client.get('/merchants'),
    ])
    setStrategies(sRes.data)
    setMerchants(mRes.data)
    setLoading(false)
  }

  async function handleAction() {
    if (!commentModal) return
    setSubmitting(true)
    try {
      const endpoint = commentModal.action === 'approve'
        ? `/marketing/strategies/${commentModal.id}/approve`
        : `/marketing/strategies/${commentModal.id}/reject`
      await client.post(endpoint, { comment })
      message.success(commentModal.action === 'approve' ? '已批准并执行' : '已驳回')
      setCommentModal(null); setComment(''); loadData()
    } catch (e: any) {
      message.error(e.response?.data?.detail || '操作失败')
    } finally { setSubmitting(false) }
  }

  if (loading) return <div style={{ textAlign: 'center', padding: 200 }}><Spin size="large" /></div>

  const pending = strategies.filter(s => s.status === 'pending')
  const approved = strategies.filter(s => s.status === 'approved')

  return (
    <div style={{ maxWidth: 980, margin: '0 auto', padding: '48px 0' }}>

      {/* 标题区 */}
      <div style={{ textAlign: 'center', marginBottom: 48 }}>
        <h1 style={{
          fontSize: 40, fontWeight: 600, color: '#1d1d1f',
          letterSpacing: 0, marginBottom: 8,
        }}>
          营销策略中心
        </h1>
        <p style={{ fontSize: 21, color: '#7a7a7a', letterSpacing: '0.011em' }}>
          AI 自动生成 · 小幅自动执行 · 大幅变更需审批
        </p>
      </div>

      {/* KPI 卡片 */}
      <div style={{
        display: 'grid', gridTemplateColumns: '1fr 1fr 1fr',
        gap: 24, marginBottom: 32,
      }}>
        <div style={{
          background: '#ffffff', border: '1px solid #e0e0e0', borderRadius: 18,
          padding: 24, textAlign: 'center',
        }}>
          <div style={{ fontSize: 12, color: '#7a7a7a', marginBottom: 4 }}>待审批</div>
          <div style={{ fontSize: 28, fontWeight: 600, color: '#ff9f0a' }}>{pending.length}</div>
        </div>
        <div style={{
          background: '#ffffff', border: '1px solid #e0e0e0', borderRadius: 18,
          padding: 24, textAlign: 'center',
        }}>
          <div style={{ fontSize: 12, color: '#7a7a7a', marginBottom: 4 }}>已执行</div>
          <div style={{ fontSize: 28, fontWeight: 600, color: '#30d158' }}>{approved.length}</div>
        </div>
        <div style={{
          background: '#ffffff', border: '1px solid #e0e0e0', borderRadius: 18,
          padding: 24, textAlign: 'center',
        }}>
          <div style={{ fontSize: 12, color: '#7a7a7a', marginBottom: 4 }}>总策略</div>
          <div style={{ fontSize: 28, fontWeight: 600, color: '#1d1d1f' }}>{strategies.length}</div>
        </div>
      </div>

      {/* 操作按钮 */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 32, justifyContent: 'center' }}>
        <Button icon={<ReloadOutlined />} onClick={loadData}
          style={{ height: 44, borderRadius: 9999, padding: '0 22px', fontSize: 17 }}>
          刷新
        </Button>
      </div>

      {/* 待审批策略列表 */}
      {pending.length === 0 ? (
        <div style={{
          textAlign: 'center', padding: 80, color: '#7a7a7a',
          background: '#f5f5f7', borderRadius: 18,
        }}>
          <p style={{ fontSize: 21, fontWeight: 600, marginBottom: 8 }}>暂无待审批策略</p>
          <p style={{ fontSize: 17 }}>暂无策略记录</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {pending.map(s => {
            const merchant = merchantMap[s.merchant_id]
            return (
              <div key={s.id} style={{
                background: '#ffffff', border: '1px solid #e0e0e0',
                borderRadius: 18, padding: 32,
                borderLeft: `4px solid ${merchant?.brand_color || '#0066cc'}`,
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div style={{ flex: 1 }}>
                    <Space style={{ marginBottom: 12 }}>
                      <Tag style={{ background: '#f5f5f7', border: 'none', borderRadius: 9999 }}>
                        {merchant?.name}
                      </Tag>
                      <Tag style={{ background: '#f5f5f7', border: 'none', borderRadius: 9999 }}>
                        {merchant?.main_category}
                      </Tag>
                      <Tag style={{ background: '#fff3e0', color: '#ff9f0a', border: 'none', borderRadius: 9999 }}>
                        ⚠️ 需审批
                      </Tag>
                    </Space>
                    <h3 style={{
                      fontSize: 21, fontWeight: 600, color: '#1d1d1f',
                      letterSpacing: '0.011em', marginBottom: 8,
                    }}>
                      {s.title}
                    </h3>
                    <p style={{ fontSize: 17, color: '#1d1d1f', lineHeight: 1.47, marginBottom: 16 }}>
                      {s.description}
                    </p>
                    <div style={{
                      background: '#f5f5f7', borderRadius: 11, padding: 16, marginBottom: 12,
                    }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: '#1d1d1f', marginBottom: 4 }}>
                        AI 决策理由
                      </div>
                      <div style={{ fontSize: 14, color: '#7a7a7a' }}>{s.ai_reasoning}</div>
                    </div>
                    {s.proposed_changes && Object.keys(s.proposed_changes).length > 0 && (
                      <div style={{
                        background: '#ffffff', border: '1px solid #e0e0e0',
                        borderRadius: 11, padding: 16,
                      }}>
                        <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 4 }}>变更内容</div>
                        <pre style={{
                          fontSize: 12, margin: 0, whiteSpace: 'pre-wrap',
                          color: '#7a7a7a', fontFamily: 'SF Mono, Menlo, monospace',
                        }}>
                          {JSON.stringify(s.proposed_changes, null, 2)}
                        </pre>
                      </div>
                    )}
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginLeft: 16 }}>
                    <Button type="primary" icon={<CheckOutlined />}
                      onClick={() => setCommentModal({ id: s.id, action: 'approve' })}>
                      批准
                    </Button>
                    <Button icon={<CloseOutlined />}
                      onClick={() => setCommentModal({ id: s.id, action: 'reject' })}>
                      驳回
                    </Button>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}

      {/* 已执行历史 */}
      {approved.length > 0 && (
        <div style={{ marginTop: 48 }}>
          <h2 style={{
            fontSize: 28, fontWeight: 600, color: '#1d1d1f',
            letterSpacing: 0, marginBottom: 24,
          }}>
            已执行策略
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {approved.slice(0, 10).map(s => {
              const merchant = merchantMap[s.merchant_id]
              return (
                <div key={s.id} style={{
                  background: '#f5f5f7', borderRadius: 11, padding: '12px 16px',
                  display: 'flex', alignItems: 'center', gap: 12,
                }}>
                  <Tag style={{
                    background: '#ffffff', border: '1px solid #e0e0e0',
                    borderRadius: 9999, fontSize: 12,
                  }}>
                    {merchant?.name}
                  </Tag>
                  <span style={{ fontSize: 14, color: '#1d1d1f', flex: 1 }}>{s.title}</span>
                  <span style={{ fontSize: 12, color: '#30d158' }}>✓ 已执行</span>
                </div>
              )
            })}
          </div>
        </div>
      )}

      <Modal
        title={commentModal?.action === 'approve' ? '批准策略' : '驳回策略'}
        open={!!commentModal}
        onOk={handleAction}
        onCancel={() => { setCommentModal(null); setComment('') }}
        confirmLoading={submitting}
        okText={commentModal?.action === 'approve' ? '确认批准' : '确认驳回'}
        okButtonProps={{ danger: commentModal?.action === 'reject' }}
      >
        <TextArea rows={3} placeholder="输入批注（可选）..." value={comment}
          onChange={e => setComment(e.target.value)} />
      </Modal>
    </div>
  )
}

// frontend/src/pages/MarketingApproval.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { CheckOutlined, CloseOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import client from '../api/client'
import { getStrategies, approveStrategy, rejectStrategy } from '../api/marketing'

interface Strategy {
  id: number
  merchant_id: number
  strategy_type: string
  title: string
  description: string
  proposed_changes: Record<string, any>
  status: string
  ai_reasoning: string
  admin_comment: string
  created_at: string | null
}

const AI_LABELS: Record<string, string> = {
  GLM: 'GLM', gpt: 'GPT', MiniMax: 'MiniMax', Kimi: 'Kimi', qwen: '通义千问',
}
const AI_COLORS: Record<string, string> = {
  GLM: '#6366f1', gpt: '#10b981', MiniMax: '#f59e0b', Kimi: '#ef4444', qwen: '#3b82f6',
}
const TYPE_LABELS: Record<string, string> = {
  price_adjustment: '调价', promotion: '促销活动',
  bundle: '捆绑销售', recommendation_update: '推荐更新',
}
const STATUS_LABELS: Record<string, string> = {
  pending: '待审批', approved: '已批准', rejected: '已驳回', executed: '已执行',
}
const STATUS_COLORS: Record<string, string> = {
  pending: 'orange', approved: 'green', rejected: 'red', executed: 'blue',
}

const strategies = ref<Strategy[]>([])
const merchants = ref<Record<number, any>>({})
const loading = ref(true)
const commentModal = ref<{ id: number; action: 'approve' | 'reject' } | null>(null)
const comment = ref('')
const submitting = ref(false)

const pendingStrategies = computed(() => strategies.value.filter(s => s.status === 'pending'))
const executedCount = computed(() => strategies.value.filter(s => s.status === 'executed').length)

async function loadAll() {
  loading.value = true
  try {
    const [stRes, mRes] = await Promise.all([
      getStrategies({}),
      client.get('/merchants'),
    ])
    strategies.value = Array.isArray(stRes.data) ? stRes.data : []
    const map: Record<number, any> = {}
    for (const m of mRes.data) {
      map[m.id] = m
    }
    merchants.value = map
  } catch (e) {
    console.error('加载失败', e)
  }
  loading.value = false
}

async function handleAction() {
  if (!commentModal.value) return
  submitting.value = true
  try {
    const { id, action } = commentModal.value
    if (action === 'approve') {
      await approveStrategy(id, comment.value)
    } else {
      await rejectStrategy(id, comment.value)
    }
    message.success(action === 'approve' ? '已批准' : '已驳回')
    commentModal.value = null
    comment.value = ''
    loadAll()
  } catch (e: any) {
    message.error(e.response?.data?.detail || '操作失败')
  }
  submitting.value = false
}

onMounted(loadAll)
</script>

<template>
  <div style="max-width: 1100px; margin: 0 auto; padding: 48px 24px">
    <div style="text-align: center; margin-bottom: 48px">
      <h1 style="font-size: 40px; font-weight: 600; color: '#1d1d1f'; margin-bottom: 8px">营销策略审批</h1>
      <p style="font-size: 21px; color: '#7a7a7a'">AI 商家提交的策略变更需要人工审批</p>
    </div>

    <a-spin v-if="loading" size="large" style="display: block; text-align: center; padding: 100px" />

    <template v-else>
      <!-- KPI -->
      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 32px">
        <div style="background: #fff; border: 1px solid #e0e0e0; border-radius: 14px; padding: 18px; text-align: center">
          <div style="font-size: 11px; color: #7a7a7a; margin-bottom: 4px">待审批</div>
          <div style="font-size: 24px; font-weight: 700; color: #ff9f0a">{{ pendingStrategies.length }}</div>
        </div>
        <div style="background: #fff; border: 1px solid #e0e0e0; border-radius: 14px; padding: 18px; text-align: center">
          <div style="font-size: 11px; color: #7a7a7a; margin-bottom: 4px">已执行</div>
          <div style="font-size: 24px; font-weight: 700; color: #30d158">{{ executedCount }}</div>
        </div>
        <div style="background: #fff; border: 1px solid #e0e0e0; border-radius: 14px; padding: 18px; text-align: center">
          <div style="font-size: 11px; color: #7a7a7a; margin-bottom: 4px">总策略</div>
          <div style="font-size: 24px; font-weight: 700; color: #1d1d1f">{{ strategies.length }}</div>
        </div>
      </div>

      <!-- 待审批策略 -->
      <template v-if="pendingStrategies.length > 0">
        <h2 style="font-size: 20px; font-weight: 600; margin-bottom: 16px">待审批策略</h2>
        <div style="display: flex; flex-direction: column; gap: 12px">
          <div
            v-for="s in pendingStrategies"
            :key="s.id"
            style="background: #fff; border: 1px solid #e0e0e0; border-radius: 14px; padding: 20px; display: flex; justify-content: space-between; align-items: flex-start"
          >
            <div style="flex: 1">
              <div style="display: flex; gap: 8px; margin-bottom: 8px">
                <a-tag style="background: #fff3e0; color: #ff9f0a; border: none; border-radius: 9999px">
                  {{ TYPE_LABELS[s.strategy_type] || s.strategy_type }}
                </a-tag>
                <a-tag
                  v-if="merchants[s.merchant_id]"
                  :style="{ background: (AI_COLORS[merchants[s.merchant_id]?.ai_model] || '#666') + '20', color: AI_COLORS[merchants[s.merchant_id]?.ai_model] || '#666', border: 'none', borderRadius: '9999px' }"
                >
                  {{ AI_LABELS[merchants[s.merchant_id]?.ai_model] || '' }}
                </a-tag>
                <a-tag style="background: #fff3e0; color: #ff9f0a; border: none; border-radius: 9999px">⚠️ 需审批</a-tag>
              </div>
              <h3 style="font-size: 16px; font-weight: 600; margin-bottom: 4px">{{ s.title }}</h3>
              <p style="font-size: 14px; color: #1d1d1f; margin-bottom: 8px">{{ s.description }}</p>
              <div style="background: #f5f5f7; border-radius: 8px; padding: 10px; font-size: 12px; color: #7a7a7a">
                <strong>AI理由：</strong>{{ s.ai_reasoning }}
              </div>
            </div>
            <div style="display: flex; flex-direction: column; gap: 6px; margin-left: 16px">
              <a-button type="primary" size="small" @click="commentModal = { id: s.id, action: 'approve' }">
                <CheckOutlined /> 批准
              </a-button>
              <a-button size="small" @click="commentModal = { id: s.id, action: 'reject' }">
                <CloseOutlined /> 驳回
              </a-button>
            </div>
          </div>
        </div>
      </template>

      <!-- 所有策略历史 -->
      <div style="margin-top: 48px">
        <h2 style="font-size: 20px; font-weight: 600; margin-bottom: 16px">全部策略</h2>
        <div style="display: flex; flex-direction: column; gap: 8px">
          <div
            v-for="s in strategies"
            :key="s.id"
            style="background: #fff; border: 1px solid #e0e0e0; border-radius: 11px; padding: 12px 16px; display: flex; align-items: center; gap: 12px"
          >
            <a-tag :color="STATUS_COLORS[s.status] || 'default'" style="border-radius: 9999px">
              {{ STATUS_LABELS[s.status] || s.status }}
            </a-tag>
            <span style="font-weight: 600; flex: 1">{{ s.title }}</span>
            <span v-if="s.created_at" style="font-size: 12px; color: #7a7a7a">
              {{ s.created_at.slice(0, 16).replace('T', ' ') }}
            </span>
          </div>
        </div>
      </div>
    </template>

    <!-- 审批弹窗 -->
    <a-modal
      :title="commentModal?.action === 'approve' ? '批准策略' : '驳回策略'"
      :open="!!commentModal"
      @ok="handleAction"
      @cancel="commentModal = null; comment = ''"
      :confirm-loading="submitting"
      :ok-text="commentModal?.action === 'approve' ? '确认批准' : '确认驳回'"
      :ok-button-props="{ danger: commentModal?.action === 'reject' }"
    >
      <a-textarea
        v-model:value="comment"
        :rows="3"
        placeholder="输入批注（可选）..."
      />
    </a-modal>
  </div>
</template>
