// frontend/src/pages/OrderHistory.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import { useCustomerStore } from '../stores/customer'
import { getOrders } from '../api/orders'

const customerStore = useCustomerStore()
const orders = ref<any[]>([])
const loading = ref(true)

const current = computed(() => customerStore.current)

const STATUS_MAP: Record<string, { label: string; color: string }> = {
  pending: { label: '待支付', color: 'orange' },
  paid: { label: '已支付', color: 'blue' },
  shipped: { label: '已发货', color: 'cyan' },
  completed: { label: '已完成', color: 'green' },
  cancelled: { label: '已取消', color: 'default' },
}

watch(() => current.value?.id, (id) => {
  if (id) {
    loading.value = true
    getOrders(id).then((res) => {
      orders.value = res.data
      loading.value = false
    })
  }
}, { immediate: true })
</script>

<template>
  <div style="max-width: 800px; margin: 0 auto; padding: 48px 0">
    <h3 style="font-size: 21px; font-weight: 600; margin-bottom: 24px">📦 我的订单</h3>

    <a-empty v-if="!current" description="请先选择身份" />

    <a-spin v-else-if="loading" style="display: block; text-align: center; padding: 60px" />

    <a-empty v-else-if="orders.length === 0" description="暂无订单" />

    <template v-else>
      <a-card
        v-for="order in orders"
        :key="order.id"
        style="margin-bottom: 12px"
      >
        <div style="display: flex; justify-content: space-between; margin-bottom: 8px">
          <span>订单号: {{ order.id }}</span>
          <a-tag :color="STATUS_MAP[order.status]?.color || 'default'">
            {{ STATUS_MAP[order.status]?.label || order.status }}
          </a-tag>
        </div>
        <div
          v-for="item in order.items"
          :key="item.id"
          style="display: flex; justify-content: space-between; padding: 4px 0"
        >
          <span>商品#{{ item.product_id }} × {{ item.quantity }}</span>
          <span>¥{{ (item.unit_price * item.quantity).toFixed(2) }}</span>
        </div>
        <div style="text-align: right; margin-top: 8px">
          <span style="font-weight: 600; color: #ff4d4f; font-size: 16px">
            合计: ¥{{ order.total_amount }}
          </span>
        </div>
      </a-card>
    </template>
  </div>
</template>

// frontend/src/pages/OrderHistory.tsx
import { useEffect, useState } from 'react'
import { Card, Typography, Tag, List, Empty, Descriptions, Spin } from 'antd'
import { useCustomerStore } from '../stores/customerStore'
import { getOrders } from '../api/orders'

const { Title, Text } = Typography

const STATUS_MAP: Record<string, { label: string; color: string }> = {
  pending: { label: '待支付', color: 'orange' },
  paid: { label: '已支付', color: 'blue' },
  shipped: { label: '已发货', color: 'cyan' },
  completed: { label: '已完成', color: 'green' },
  cancelled: { label: '已取消', color: 'default' },
}

export default function OrderHistory() {
  const { current } = useCustomerStore()
  const [orders, setOrders] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (current) {
      setLoading(true)
      getOrders(current.id).then((res) => {
        setOrders(res.data)
        setLoading(false)
      })
    }
  }, [current?.id])

  if (!current) return <Empty description="请先选择身份" />
  if (loading) return <div style={{ textAlign: 'center', padding: 60 }}><Spin /></div>

  return (
    <div style={{ maxWidth: 800, margin: '0 auto' }}>
      <Title level={3}>📦 我的订单</Title>
      {orders.length === 0 ? (
        <Empty description="暂无订单" />
      ) : (
        <List
          dataSource={orders}
          renderItem={(order: any) => {
            const st = STATUS_MAP[order.status] || { label: order.status, color: 'default' }
            return (
              <Card style={{ marginBottom: 12 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                  <Text>订单号: {order.id}</Text>
                  <Tag color={st.color}>{st.label}</Tag>
                </div>
                {order.items?.map((item: any) => (
                  <div key={item.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '4px 0' }}>
                    <Text>商品#{item.product_id} × {item.quantity}</Text>
                    <Text>¥{(item.unit_price * item.quantity).toFixed(2)}</Text>
                  </div>
                ))}
                <div style={{ textAlign: 'right', marginTop: 8 }}>
                  <Text strong style={{ color: '#ff4d4f', fontSize: 16 }}>
                    合计: ¥{order.total_amount}
                  </Text>
                </div>
              </Card>
            )
          }}
        />
      )}
    </div>
  )
}
